import { useState } from 'react';
import { CloudUpload, Play, Terminal, CheckCircle } from 'lucide-react';
import { API_BASE_URL } from '../config';

export default function UploadPage() {
  const [file, setFile] = useState<File | null>(null);
  const [collection, setCollection] = useState<string>('product_descriptions');
  const [statusText, setStatusText] = useState<string>('Ready to ingest new documents.');
  const [loading, setLoading] = useState<boolean>(false);
  const [bulkLoading, setBulkLoading] = useState<boolean>(false);
  const [progress, setProgress] = useState<number>(0);
  const [logs, setLogs] = useState<string[]>(['[SYSTEM] Ingestion engine standby.']);

  const addLog = (message: string) => {
    setLogs((prev) => [...prev, `[${new Date().toLocaleTimeString()}] ${message}`]);
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      setFile(e.target.files[0]);
      setStatusText(`Selected: ${e.target.files[0].name}`);
      addLog(`File selected: ${e.target.files[0].name} (${(e.target.files[0].size / 1024).toFixed(1)} KB)`);
    }
  };

  const handleSingleIngest = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!file) {
      alert('Please select a file to upload first.');
      return;
    }

    try {
      setLoading(true);
      setProgress(10);
      setStatusText('Uploading file to temp storage...');
      addLog(`Uploading '${file.name}' to server temporary folder...`);

      // Step 1: Upload to temp storage
      const formData = new FormData();
      formData.append('file', file);
      
      const uploadRes = await fetch(`${API_BASE_URL}/api/upload`, {
        method: 'POST',
        body: formData
      });

      if (!uploadRes.ok) {
        const errData = await uploadRes.json();
        throw new Error(errData.error || 'Failed to upload file.');
      }

      setProgress(40);
      const uploadData = await uploadRes.json();
      setStatusText('Processing text extraction and embeddings...');
      addLog(`Upload success. Path: ${uploadData.filePath}`);
      addLog('Extracting text and calculating 384-dimensional vector embeddings...');

      // Step 2: Trigger Ingest pipeline
      setProgress(60);
      const ingestRes = await fetch(`${API_BASE_URL}/api/ingest`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          filePath: uploadData.filePath,
          originalName: uploadData.originalName,
          collection: collection
        })
      });

      if (!ingestRes.ok) {
        const errData = await ingestRes.json();
        throw new Error(errData.error || 'Failed to index file.');
      }

      setProgress(100);
      const ingestData = await ingestRes.json();
      setStatusText(`Success! '${file.name}' ingested completely.`);
      addLog(`[SUCCESS] Ingested into collection '${collection}'. Generated ${ingestData.document.chunk_count} chunks inside ChromaDB.`);
      setFile(null);
    } catch (err: any) {
      setProgress(0);
      setStatusText(`Error: ${err.message}`);
      addLog(`[ERROR] ${err.message}`);
    } finally {
      setLoading(false);
    }
  };

  const handleBulkIngest = async () => {
    if (!window.confirm('This will trigger automated indexing for all 52 documents generated by the dataset generator. Proceed?')) {
      return;
    }

    try {
      setBulkLoading(true);
      setProgress(20);
      setStatusText('Scanning test dataset folders...');
      addLog('Scanning root data/sample_dataset/ directory...');

      setProgress(50);
      setStatusText('Calculating embeddings and filling ChromaDB...');
      addLog('Processing 52 product descriptions, manuals, FAQs, warranties, and return/shipping policies...');
      addLog('Generating local vectors (Xenova/all-MiniLM-L6-v2) for all chunks. Please wait (takes ~15-30s)...');

      const res = await fetch(`${API_BASE_URL}/api/documents/ingest-sample`, { method: 'POST' });
      
      if (!res.ok) {
        const errData = await res.json();
        throw new Error(errData.error || 'Failed bulk ingestion.');
      }

      setProgress(100);
      const data = await res.json();
      setStatusText('Automated dataset ingestion complete!');
      addLog(`[SUCCESS] Automated Ingest complete. Ingested: ${data.ingestedCount} documents. Skipped: ${data.skippedCount} duplicates.`);
    } catch (err: any) {
      setProgress(0);
      setStatusText(`Bulk Error: ${err.message}`);
      addLog(`[ERROR] Bulk Ingest failed: ${err.message}`);
    } finally {
      setBulkLoading(false);
    }
  };

  return (
    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1.2fr', gap: '32px', height: '100%' }}>
      {/* Left panel: Single upload and Bulk trigger */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '32px' }}>
        
        {/* Single File Ingestion Card */}
        <section className="glass-card">
          <h3 style={{ marginBottom: '18px', color: '#ffffff', display: 'flex', alignItems: 'center', gap: '10px' }}>
            <CloudUpload size={20} color="var(--primary)" />
            <span>Single File Ingestion</span>
          </h3>

          <form onSubmit={handleSingleIngest} style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
            <label className="drag-drop-zone">
              <CloudUpload size={40} color="var(--text-muted)" />
              <div style={{ fontSize: '15px', color: 'white', fontWeight: 600 }}>Drag & Drop or Click to Select File</div>
              <div style={{ fontSize: '12px', color: 'var(--text-disabled)' }}>Supports PDF, DOCX, CSV, TXT, MD (Max 15MB)</div>
              <input 
                type="file" 
                style={{ display: 'none' }} 
                onChange={handleFileChange}
                accept=".pdf,.docx,.csv,.txt,.md,.markdown" 
              />
            </label>

            {file && (
              <div style={{ padding: '10px 14px', background: 'rgba(255, 255, 255, 0.02)', border: '1px solid var(--border-glass)', borderRadius: '8px', fontSize: '13px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                <CheckCircle size={14} color="var(--success)" />
                <span style={{ fontWeight: 500, color: 'white' }}>Selected:</span> {file.name}
              </div>
            )}

            <div>
              <label style={{ display: 'block', fontSize: '13px', color: 'var(--text-muted)', marginBottom: '8px', fontWeight: 500 }}>Target Vector Collection:</label>
              <select 
                className="input-control"
                value={collection}
                onChange={(e) => setCollection(e.target.value)}
                style={{ background: 'rgba(0, 0, 0, 0.3)', border: '1px solid var(--border-glass)' }}
              >
                <option value="product_descriptions">Product Descriptions (product_descriptions)</option>
                <option value="manuals">User Manuals (manuals)</option>
                <option value="faqs">FAQ Documents (faqs)</option>
                <option value="warranty">Warranty Terms (warranty)</option>
                <option value="returns">Return Policies (returns)</option>
                <option value="shipping">Shipping Rules (shipping)</option>
              </select>
            </div>

            <button 
              type="submit" 
              className="btn btn-primary"
              disabled={loading || bulkLoading || !file}
              style={{ width: '100%', opacity: !file ? 0.6 : 1 }}
            >
              <Play size={16} />
              <span>{loading ? 'Ingesting File...' : 'Start Ingest Pipeline'}</span>
            </button>
          </form>
        </section>

        {/* Bulk Automator Card */}
        <section className="glass-card" style={{ border: '1px solid var(--border-glass-glow)', background: 'linear-gradient(135deg, rgba(14, 18, 36, 0.8), rgba(100, 80, 250, 0.02))' }}>
          <h3 style={{ marginBottom: '8px', color: '#ffffff' }}>Bulk Dataset Automator</h3>
          <p style={{ fontSize: '13px', color: 'var(--text-muted)', marginBottom: '20px', lineHeight: 1.4 }}>
            Click below to scan the generated test dataset folder and auto-index all 52 high-quality product manuals, descriptions, and policies into ChromaDB instantly.
          </p>
          <button 
            className="btn btn-secondary" 
            style={{ width: '100%', border: '1px solid var(--border-glass-glow)' }}
            onClick={handleBulkIngest}
            disabled={loading || bulkLoading}
          >
            <span>{bulkLoading ? 'Auto-indexing 52+ Files...' : 'Automate 50+ Ingestion'}</span>
          </button>
        </section>
      </div>

      {/* Right panel: Active status & streaming console logs */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
        
        {/* Status display */}
        <div className="glass-card" style={{ padding: '20px 24px' }}>
          <div style={{ fontSize: '12px', textTransform: 'uppercase', color: 'var(--text-disabled)', letterSpacing: '0.05em', marginBottom: '4px' }}>Current Process Status</div>
          <div style={{ fontSize: '16px', fontWeight: 600, color: 'white', display: 'flex', alignItems: 'center', gap: '10px' }}>
            <span className="status-dot" style={{ 
              backgroundColor: loading || bulkLoading ? 'var(--warning)' : 'var(--success)',
              boxShadow: loading || bulkLoading ? '0 0 8px var(--warning)' : '0 0 8px var(--success)',
              animation: loading || bulkLoading ? 'pulse 1.5s infinite' : 'none'
            }} />
            <span>{statusText}</span>
          </div>

          {(loading || bulkLoading) && (
            <div className="progress-bar-container">
              <div className="progress-bar-fill" style={{ width: `${progress}%` }} />
            </div>
          )}
        </div>

        {/* Real-time streaming console log */}
        <div className="glass-card" style={{ flexGrow: 1, display: 'flex', flexDirection: 'column', padding: '24px', background: 'rgba(0, 0, 0, 0.4)' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px', borderBottom: '1px solid var(--border-glass)', paddingBottom: '10px' }}>
            <span style={{ fontSize: '14px', fontWeight: 700, color: 'white', display: 'flex', alignItems: 'center', gap: '8px' }}>
              <Terminal size={16} color="var(--primary)" />
              <span>Real-time Ingest Console Logs</span>
            </span>
            <button 
              style={{ fontSize: '11px', background: 'transparent', border: 'none', color: 'var(--text-disabled)', cursor: 'pointer' }}
              onClick={() => setLogs(['[SYSTEM] Console logs cleared.'])}
            >
              Clear Logs
            </button>
          </div>

          <div style={{ 
            flexGrow: 1, 
            background: '#04060f', 
            borderRadius: '8px', 
            padding: '16px', 
            fontFamily: 'monospace', 
            fontSize: '12px', 
            color: '#c5cbef', 
            overflowY: 'auto',
            height: '350px',
            lineHeight: 1.6
          }}>
            {logs.map((log, idx) => (
              <div key={idx} style={{ 
                borderBottom: '1px solid rgba(255, 255, 255, 0.01)',
                padding: '4px 0',
                color: log.includes('[ERROR]') ? 'var(--danger)' : log.includes('[SUCCESS]') ? 'var(--success)' : '#c5cbef'
              }}>
                {log}
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
